name: Build, Publish and Deploy to SmarterASP.NET

on:
  push:
    branches:
      - master   # change if your branch is different

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore
        run: dotnet restore

      # Build project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish project
      - name: Publish
        run: dotnet publish
        #run: dotnet publish ./YOUR_PROJECT_NAME/YOUR_PROJECT_NAME.csproj --configuration Release --output ./publish

      # Run tests (optional)
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Deploy to SmarterASP.NET
      - name: Deploy to SmarterASP.NET
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: ./publish
